krdp: fix service filename
Service file was renamed in f1647b657f3af89f51cb7641760cf29311e0506b.

plasma-krdp_server.service --> app-org.kde.krdpserver.service

Fixes the following error:

ERROR: krdp-6.3.4-r0 do_package: Didn't find service unit 'plasma-krdp_server.service', specified in SYSTEMD_SERVICE:krdp.

Signed-off-by: Marc Ferland <marc.ferland@sonatest.com>