plasma-mobile.inc: fix buildpaths qa issue
While migrating to walnascar we get:
```
ERROR: plasma-mobile-6.3.4-r0 do_package_qa: QA Issue: File /usr/src/debug/plasma-mobile/6.3.4/components/mobileshellstate/mobileadaptor.h in package plasma-mobile-src contains reference to TMPDIR [buildpaths]
ERROR: plasma-mobile-6.3.4-r0 do_package_qa: Fatal QA errors were found, failing task.
```

Fix the path so that it's possible to do reproducible builds.