kwin: fix packaging error
New file was added:

ERROR: kwin-6.5.2-r0 do_package: QA Issue: kwin: Files/directories were installed but not shipped in any package:
  /usr/lib/kconf_update_bin/kwin-6.5-showpaint-changes
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.

Signed-off-by: Marc Ferland <marc.ferland@sonatest.com>