plasma-pa: fix build
Stop runtime depending on libcanberra-pulseaudio and libcanberra-alsa
in plasma-pa to fix:

ERROR: plasma-pa-6.6.5-r0 do_package_qa: QA Issue: plasma-pa rdepends
on libcanberra-pulseaudio, but it isn't a build dependency?
[build-deps]

Instead, fix the libcanberra-pulseaudio/alsa packages so that they
runtime-depend on libcanberra.

Signed-off-by: Marc Ferland <marc.ferland@gmail.com>