plasma-workspace: add missing files
Files are missing from the plasma-workspace package:

ERROR: plasma-workspace-6.5.2-r0 do_package: QA Issue: plasma-workspace: Files/directories were installed but not shipped in any package:
  /usr/lib/libklookandfeel.so
  /usr/share/kxmlgui5/kfontviewpart
  /usr/share/kxmlgui5/kfontviewpart/kfontviewpart.rc

Signed-off-by: Marc Ferland <marc.ferland@sonatest.com>