krdp: add missing file
Fix for:

ERROR: krdp-6.5.2-r0 do_package: QA Issue: krdp: Files/directories were installed but not shipped in any package:
  /usr/lib/systemd/user-preset/00-krdp.preset

Signed-off-by: Marc Ferland <marc.ferland@sonatest.com>