plasma-mobile: fix license checksum error
ERROR: plasma-mobile-6.2.4-r0 do_populate_lic: QA Issue: plasma-mobile: The LIC_FILES_CHKSUM does not match for file://LICENSES/LGPL-3.0-only.txt;md5=8d51f5b5fd447f7a1040c3dc9f0a8de6
plasma-mobile: The new md5 checksum is 1a523aee720780ffc0705c5bf17a6421

Caused by commit: eb9509ce68f2f92ac8ed8426bde0c95330805def

Signed-off-by: Marc Ferland <marc.ferland@gmail.com>