packagekit: fix build failure
ERROR: packagekit-1.3.2-r0 do_package_qa: QA Issue: File /usr/lib/libpackagekit-glib2.so.18.1.3 in package packagekit contains reference to TMPDIR [buildpaths]
ERROR: packagekit-1.3.2-r0 do_package_qa: Fatal QA errors were found, failing task.

In libpackagekit-glib2, the TESTDATADIR preprocessor define is used
only for the test infrastructure. It provides the path to a directory
containing test data files used by unit tests or mock backends during
development and automated testing. Unfortunately it is baked in, this
patch adds an INSANE_SKIP to silence the build error.

Signed-off-by: Marc Ferland <marc.ferland@gmail.com>