krdp: disable krdp_server user service
User services cannot be enabled at do_rootfs time. They generate
errors similar to:

ERROR: image-1.0-r0 do_rootfs: Error: Systemctl main enable issue in plasma-krdp_server.service (plasma-krdp_server.service)
ERROR: image-1.0-r0 do_rootfs: Postinstall scriptlets of ['krdp'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.
Details of the failure are in /path/to/tmp/work/machine/image/1.0/temp/log.do_rootfs.
ERROR: Logfile of failure stored in: /path/to/tmp/work/machine/image/1.0/temp/log.do_rootfs.123456
ERROR: Task (/path/to/image.bb:do_rootfs) failed with exit code '1

Note that the service _will_ be activated when users turn on the krdp
server from the system settings UI. So actually activating it from the
recipe is not really what we want anyway.

Signed-off-by: Marc Ferland <marc.ferland@sonatest.com>