plasma-mobile: add missing files
Files are missing from the package:

ERROR: plasma-mobile-6.5.2-r0 do_package: QA Issue: plasma-mobile: Files/directories were installed but not shipped in any package:
  /usr/lib/qml/org/kde/plasma/quicksetting/kscreenosd/qmldir
  /usr/lib/qml/org/kde/plasma/quicksetting/kscreenosd/libkscreenosdplugin.so

Signed-off-by: Marc Ferland <marc.ferland@sonatest.com>